### ISSUE TITLE
It is necessary to provide compiler flow. Can README.md be detailed?

### ISSUE THREAD

**Issue by nisang** [HcashOrg/HX-IDE#1]
It is necessary to provide compiler flow. Can README.md be detailed?

**Comment by vaststar** [comment]
Thanks for reminding. The IDE is not available yet. It should be used with some necessary components we provide such as codemirror-editor and uvm.
 Actually, its usage is designed to be similar to ordinary  ide's which can be summarized as write your contract-code and just comiler it.
